spring:
  application:
    name: emergence-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/dingchao_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: dingchao
    password: 6049773e1914457d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lynn.emergence.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.lynn.emergence: info
    org.springframework.web: info
    org.apache.ibatis: warn
    org.mybatis: warn
